import os
os.system('./carbon TC_LEN_001')
os.system('./carbon TC_LEN_002')
os.system('./carbon TC_LEN_003')
os.system('./carbon TC_LEN_004')
os.system('./carbon TC_LEN_005')
os.system('./carbon TC_LEN_006')
os.system('./carbon TC_LEN_007')
os.system('./carbon TC_LEN_008')
